baseURL = "www.nathom.dev"
relativeURLs = true
languageCode = 'en-us'
title = 'Thinkings'
theme = 'hugo-theme-gruvbox'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      # This setting allows inlining <script> and <style> tags in markdown, 
      # which is useful and required to use Prism plugins, but may be dangerous 
      # if the content isn't trustworthy.
      unsafe = true

[imaging]
  # JPEG and WebP image processing quality, defaults to 75%
  quality = 100

[params]
  defaultTheme = "dark"
  # gray red green yellow blue purple aqua orange, defaults to blue
  themeColor = "blue"
  # soft medium hard, defaults to medium
  themeContrast = "medium"
  author = "Nathan Thomas"
  subtitle = "A blog"
  description = "A free space"
  comments = true

  [params.Giscus]
    repo              = "nathom/thinkings_comments"
    repo_id           = "R_kgDOKDmHRQ"
    category          = "General"
    category_id       = "DIC_kwDOKDmHRc4CYXMZ"
    reactions_enabled = "1"
    input_position    = "bottom"
    theme             = "noborder_dark"



  [params.logo]
    text = "thinkings"
    url = "/"

  [params.prism]
    languages = [
      "markup",
      "c",
      "rust",
      "python",
      "haskell",
      "css",
      "clike",
      "javascript",
      "bash",
      "diff",
      "toml",
      "armasm",
      "lua",
      "applescript",
    ]
    plugins = [
      "normalize-whitespace",
      "toolbar",
      "copy-to-clipboard",
      "line-numbers",
      "command-line",
      "diff-highlight"
    ]
  
  # By default, the theme creates resized versions of images ranging from 300 to
  # 700 pixels wide in increments of 200 pixels
  #[params.imageResize]
  #  min = 300
  #  max = 700
  #  increment = 200
  
  [params.tagCloud]
    enable         = false
    minFontSizeRem = 0.8
    maxFontSizeRem = 2.0

  # Social share links for posts:
  #   - iconSuite: "simple-icon" or "tabler-icon"
  #   - iconName: name of the icon from the "iconSuite"
  #   - {url} placeholder for post .Permalink
  #   - {title} placeholder for post .Title
  # See  https://github.com/bradvin/social-share-urls for more format strings
  [[params.socialShare]]
    iconSuite             =  "simple-icon"
    iconName              =  "facebook"
    formatString          =  "https://www.facebook.com/sharer.php?u={url}"
  [[params.socialShare]]
    iconSuite             =  "simple-icon"
    iconName              =  "reddit"
    formatString          =  "https://reddit.com/submit?url={url}&title={title}"
  [[params.socialShare]]
    iconSuite             =  "simple-icon"
    iconName              =  "twitter"
    formatString          =  "https://twitter.com/intent/tweet?url={url}&text={title}"
  [[params.socialShare]]
    iconSuite             =  "simple-icon"
    iconName              =  "linkedin"
    formatString          =  "https://www.linkedin.com/sharing/share-offsite/?url={url}"
  [[params.socialShare]]
    iconSuite             =  "simple-icon"
    iconName              =  "whatsapp"
    formatString          =  "whatsapp://send/?text={title}%20{url}"
  [[params.socialShare]]
    iconSuite             =  "simple-icon"
    iconName              =  "tumblr"
    formatString          =  "https://www.tumblr.com/widgets/share/tool?canonicalUrl={url}&title={title}&caption={title}"
  [[params.socialShare]]
    iconSuite             =  "simple-icon"
    iconName              =  "pinterest"
    formatString          =  "http://pinterest.com/pin/create/button/?url={url}"
  [[params.socialShare]]
    iconSuite             =  "simple-icon"
    iconName              =  "ycombinator"
    formatString          =  "https://news.ycombinator.com/submitlink?u={url}&t={title}"
  [[params.socialShare]]
    iconSuite             =  "simple-icon"
    iconName              =  "vk"
    formatString          =  "http://vk.com/share.php?url={url}&title={title}&comment={title}"
  [[params.socialShare]]
    iconSuite             =  "simple-icon"
    iconName              =  "xing"
    formatString          =  "https://www.xing.com/spi/shares/new?url={url}"
  [[params.socialShare]]
    iconSuite             =  "simple-icon"
    iconName              =  "telegram"
    formatString          =  "https://telegram.me/share/url?url={url}&text={title}"
  [[params.socialShare]]
    iconSuite             =  "tabler-icon"
    iconName              =  "mail"
    formatString          =  "mailto:?subject={title}&body={url}"

[menu]
  # [[menu.main]]
  #   identifier = "blog"
  #   name = "Blog"
  #   url = "/blog"
  #   weight = 10
  # [[menu.main]]
  #   identifier = "cv"
  #   name = "CV"
  #   url = "/cv"
  #   weight = 20
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about"
    weight = 30

[languages]
  [languages.en]
    languageName = "English"
    weight = 10
    [languages.en.params.jsonResume]
      present = "present"

[build]
  # The theme enables writeStats which is required for PurgeCSS
  _merge = "deep"

# This hopefully will be simpler in the future.
# See: https://github.com/schnerring/hugo-theme-gruvbox/issues/16
[module]
  [[module.imports]]
    path = "github.com/schnerring/hugo-mod-json-resume"
    [[module.imports.mounts]]
      source = "data"
      target = "data"
    [[module.imports.mounts]]
      source = "layouts"
      target = "layouts"
    [[module.imports.mounts]]
      source = "assets/css/json-resume.css"
      target = "assets/css/critical/44-json-resume.css"
  [[module.mounts]]
    # required by hugo-mod-json-resume
    source = "node_modules/simple-icons/icons"
    target = "assets/simple-icons"
  [[module.mounts]]
    source = "assets"
    target = "assets"
  [[module.mounts]]
    source = "layouts"
    target = "layouts"
  [[module.mounts]]
    source = "static"
    target = "static"
  [[module.mounts]]
    source = "node_modules/prismjs"
    target = "assets/prismjs"
  [[module.mounts]]
    source = "node_modules/prism-themes/themes"
    target = "assets/prism-themes"
  [[module.mounts]]
    source = "node_modules/typeface-fira-code/files"
    target = "static/fonts"
  [[module.mounts]]
    source = "node_modules/typeface-roboto-slab/files"
    target = "static/fonts"
  [[module.mounts]]
    source = "node_modules/@tabler/icons/icons"
    target = "assets/tabler-icons"
